export const GET_DOGS = "GET_DOGS";
export const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
export const GET_RAZAS = "GET_RAZAS";
export const GET_DOGS_DETAIL_RAZA = "GET_DOGS_DETAIL_RAZA";
export const GET_DOGS_SEARCH = "GET_DOGS_SEARCH";
export const GET_CLEANAP_DOGS = "GET_CLEANAP_DOGS";
export const GET_CLEANAP_DOGS_BY_ID = "GET_CLEANAP_DOGS_BY_ID";